spring.application.name=estoque-service
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/estoque}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:estoque}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:estoque}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
